# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.Produto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.Cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.Funcionario')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
